services:
  node_app:
    image: node_app
    restart: always
    build: 
      context: .
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16.0
    hostname: cardsdb.dev
    restart: always
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - "./backend/db:/docker-entrypoint-initdb.d"